-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admins
(
    id serial NOT NULL,
    login character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Администратор'::character varying,
    is_read_only boolean DEFAULT false,
    CONSTRAINT admins_pkey PRIMARY KEY (id),
    CONSTRAINT admins_login_key UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS public.candidate_voting
(
    candidate_id integer NOT NULL,
    voting_id integer NOT NULL,
    is_read_only boolean DEFAULT false,
    CONSTRAINT candidate_voting_pkey PRIMARY KEY (candidate_id, voting_id)
);

CREATE TABLE IF NOT EXISTS public.candidates
(
    id serial NOT NULL,
    login character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    info text COLLATE pg_catalog."default",
    created_by_commission_id integer,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Кандидат'::character varying,
    is_read_only boolean DEFAULT false,
    CONSTRAINT candidates_pkey PRIMARY KEY (id),
    CONSTRAINT candidates_login_key UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS public.central_election_commissions
(
    id serial NOT NULL,
    login character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_by_admin_id integer,
    is_read_only boolean DEFAULT false,
    CONSTRAINT central_election_commissions_pkey PRIMARY KEY (id),
    CONSTRAINT central_election_commissions_login_key UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date NOT NULL,
    snils character varying(14) COLLATE pg_catalog."default",
    login character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_read_only boolean DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_login_key UNIQUE (login),
    CONSTRAINT users_snils_key UNIQUE (snils)
);

CREATE TABLE IF NOT EXISTS public.votes
(
    id serial NOT NULL,
    user_id integer,
    voting_id integer,
    candidate_id integer,
    voted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_read_only boolean DEFAULT true, -- голоса обычно read-only
    CONSTRAINT votes_pkey PRIMARY KEY (id),
    CONSTRAINT votes_user_id_voting_id_key UNIQUE (user_id, voting_id)
);

CREATE TABLE IF NOT EXISTS public.votings
(
    id serial NOT NULL,
    commission_id integer,
    end_date date NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_read_only boolean DEFAULT false,
    CONSTRAINT votings_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.candidate_voting
    ADD CONSTRAINT candidate_voting_candidate_id_fkey FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.candidate_voting
    ADD CONSTRAINT candidate_voting_voting_id_fkey FOREIGN KEY (voting_id)
    REFERENCES public.votings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.candidates
    ADD CONSTRAINT candidates_created_by_commission_id_fkey FOREIGN KEY (created_by_commission_id)
    REFERENCES public.central_election_commissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.central_election_commissions
    ADD CONSTRAINT central_election_commissions_created_by_admin_id_fkey FOREIGN KEY (created_by_admin_id)
    REFERENCES public.admins (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.votes
    ADD CONSTRAINT votes_candidate_id_fkey FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.votes
    ADD CONSTRAINT votes_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.votes
    ADD CONSTRAINT votes_voting_id_fkey FOREIGN KEY (voting_id)
    REFERENCES public.votings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.votings
    ADD CONSTRAINT votings_commission_id_fkey FOREIGN KEY (commission_id)
    REFERENCES public.central_election_commissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;