server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
  h2:
    console:
      enabled: true
      path: /h2-console
      
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h
      
# API Documentation
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    
# Логирование
logging:
  level:
    org.example: DEBUG
    org.springframework.cache: DEBUG
    com.github.benmanes.caffeine: DEBUG
    org.springframework.cache.interceptor: TRACE
    
# Настройки приложения
app:
  pdf:
    output-directory: ./results/
  security:
    enable-basic-auth: true 